language: generic

notifications:
  email:
    on_success: never
    on_failure: never

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: ATOM_CHANNEL=stable APM_TEST_PACKAGES="" CHROME_DEVEL_SANDBOX=""
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: ATOM_CHANNEL=beta APM_TEST_PACKAGES="" CHROME_DEVEL_SANDBOX=""
    - os: osx
      language: objective-c
      env: ATOM_CHANNEL=stable APM_TEST_PACKAGES=""
    - os: osx
      language: objective-c
      env: ATOM_CHANNEL=beta APM_TEST_PACKAGES=""


env:
  global:
    - APM_TEST_PACKAGES=""


addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

node_js: lts/*

after_success:
  # Add apm to the PATH
  - export PATH=${PATH}:${HOME}/atom/usr/bin/

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
